name = "web-portofolio"

[build]
command = "npm install --legacy-peer-deps && npm run build"

[site]
bucket = "./build"

[pages]
pages_build_output_dir = "./build"

[build.environment]
NODE_VERSION = "20.10.0"
NPM_FLAGS = "--force"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200