name = "web-portofolio"

[build]
command = "npm install --force && npm run build"
upload.format = "service-worker"

[site]
bucket = "./build"

[build.environment]
NODE_VERSION = "20.10.0"
NPM_FLAGS = "--force"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[env.production]
bucket = "./build"
route = "yourdomain.com/*"
zone_id = "your-zone-id"